# 01. Importing Libraries

In [2]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd
import scipy.stats as st
import re

# 02. Importing Data

In [3]:
books = pd.read_csv('../01. Data/books_with_clusters.csv')

# 03. Beautification of Database

In [4]:
books.head()

,book_id,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url,cluster,genres_clean
0,0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,2008,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374.0,The Hunger Games#1,NaN,NaN,NaN,NaN,NaN,4,"Young Adult, Dystopia, Fiction, Fantasy, Scien..."
1,1,Pride and Prejudice,Jane Austen,4.30,4920467.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,1813,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Classics, Romance, Fiction, Historical Fiction..."
2,2,To Kill a Mockingbird,Harper Lee,4.26,7016855.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,1960,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323.0,To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN,2,"Classics, Fiction, Historical Fiction, Literat..."
3,3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,2003,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896.0,Harry Potter#5,NaN,NaN,NaN,NaN,NaN,4,"Fantasy, Fiction, Young Adult, Fantasy, Childrens"
4,4,The Book Thief,Markus Zusak,4.39,2935583.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,2005,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Historical Fiction, Fiction, Young Adult, Clas..."

In [5]:
# retting index to be book_id
books.set_index('book_id', inplace=True)

In [6]:
# changing num_ratings and pages into INT
books['num_ratings'] = books['num_ratings'].astype('Int64')
books['pages'] = books['pages'].astype('Int64')

In [7]:
books.head()

,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url,cluster,genres_clean
book_id,,,,,,,,,,,,,,,,,,,
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,2008,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374,The Hunger Games#1,NaN,NaN,NaN,NaN,NaN,4,"Young Adult, Dystopia, Fiction, Fantasy, Scien..."
1,Pride and Prejudice,Jane Austen,4.30,4920467,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,1813,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279,NaN,NaN,NaN,NaN,NaN,NaN,2,"Classics, Romance, Fiction, Historical Fiction..."
2,To Kill a Mockingbird,Harper Lee,4.26,7016855,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,1960,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323,To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN,2,"Classics, Fiction, Historical Fiction, Literat..."
3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,2003,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896,Harry Potter#5,NaN,NaN,NaN,NaN,NaN,4,"Fantasy, Fiction, Young Adult, Fantasy, Childrens"
4,The Book Thief,Markus Zusak,4.39,2935583,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,2005,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592,NaN,NaN,NaN,NaN,NaN,NaN,2,"Historical Fiction, Fiction, Young Adult, Clas..."

In [8]:
books.isnull().sum()

title                0
author               0
avg_rating         755
num_ratings        733
cover_img_url        4
goodreads_url     1000
source               0
year_published       0
genres               0
description          0
pages               24
series            1529
isbn              1008
publisher         1009
language          1004
ol_key            1004
google_url        1017
cluster              0
genres_clean         0
dtype: int64

In [9]:
# stripping " " from title and author columns
books['title'] = books['title'].str.strip().str.strip('"')
books['author'] = books['author'].str.strip().str.strip('"')

In [10]:
# checking if books with " " in the name were stripped correctly
books[books['title'].str.contains('paint', case=False)][['title', 'genres']]

,title,genres
book_id,,
1121,Painted Scars,"Romance, Dark, Contemporary Romance, Adult, Di..."
1784,I Heard You Paint Houses,"Nonfiction, True Crime"

In [11]:
# removing duplicated genres from genres_list
def remove_duplicate_genres(genre_list):
    seen = []
    for genre in genre_list:
        if genre not in seen:
            seen.append(genre)
    return seen

def clean_genres_string(genres_string):
    genre_list = genres_string.split(', ')
    unique_genres = remove_duplicate_genres(genre_list)
    return ', '.join(unique_genres)

books['genres_clean'] = books['genres_clean'].apply(clean_genres_string)

In [12]:
# checking if duplicated genres were removed correctly
books[books['author'].str.contains('Agatha Christie', case=False)][['title', 'genres_clean']]

,title,genres_clean
book_id,,
92,And Then There Were None,"Mystery, Classics, Fiction, Thriller, Crime"
215,"Murder on the Orient Express (Hercule Poirot, ...","Mystery, Classics, Fiction, Crime, Thriller"
801,"The Murder of Roger Ackroyd (Hercule Poirot, #4)","Mystery, Fiction, Classics, Crime, Thriller"
838,"Death on the Nile (Hercule Poirot, #18)","Mystery, Fiction, Classics, Crime, Thriller"
1125,The Mystery of the Blue Train,"Crimes Against, Mystery, Fiction"
1126,Endless Night,"Fiction, Mystery"
1144,Death on the Nile,"Fiction, Mystery"

In [13]:
# allowing me to see all the rows in the dataset
pd.set_option('display.max_rows', None)

In [ ]:
# cell output was long, so it was clear from the notebook - next cells are works done based on the output of this cell
books[['title', 'author', 'description', 'series']]

In [15]:
# correcting the series column for book_id 334
books.loc[334, ['title', 'author', 'description', 'series']]

title                                 The Wind-Up Bird Chronicle
author                                           Haruki Murakami
description    Japan's most highly regarded novelist now vaul...
series                                            ねじまき鳥クロニクル#1-3
Name: 334, dtype: str

In [16]:
# changing the series
books.loc[334, 'series'] = "The Wind-Up Bird Chronicle #1-3"

In [17]:
books.loc[334, ['title', 'author', 'description', 'series']]

title                                 The Wind-Up Bird Chronicle
author                                           Haruki Murakami
description    Japan's most highly regarded novelist now vaul...
series                           The Wind-Up Bird Chronicle #1-3
Name: 334, dtype: str

In [18]:
# starndardizing the series column
books['series'] = books['series'].str.replace(r'(\S)#', r'\1 #', regex=True)

In [19]:
books.loc[642, ['title', 'author']]

title                    العصبي
author    أحمد جمال الدين رمضان
Name: 642, dtype: str

In [20]:
# checking the authors to be able to know what to correct in the author column
books.loc[[642, 634, 500, 476, 1462, 1649, 1650, 1677, 1681], ['title', 'author']]

,title,author
book_id,,
642,العصبي,أحمد جمال الدين رمضان
634,انتحار فاشل,أحمد جمال الدين رمضان
500,زندگی مه آلود پریا,سید مرتضی مصطفوی
476,القرآن الكريم,الله
1462,Before the Coffee Gets Cold,川口俊和
1649,Chto takoe iskusstvo? / What is art?,Лев Толстой
1650,Great Dialogues of Plato,Πλάτων
1677,Death's End (The Three-Body Problem Series Boo...,刘慈欣
1681,The Dark Forest (The Three-Body Problem Series...,刘慈欣

In [21]:
# correcting the autor column for roman caracters
author_corrections = {
    'أحمد جمال الدين رمضان': 'Ahmed Gamal El-Din Ramadan',
    'سید مرتضی مصطفوی': 'Seyyed Morteza Mostafavi',
    'الله': 'Anonymous',
    '川口俊和': 'Toshikazu Kawaguchi',
    'Лев Толстой': 'Leo Tolstoy',
    'Πλάττων': 'Plato',
    '刘慈欣': 'Liu Cixin',
    'Πλάτων': 'Plato'
}

books['author'] = books['author'].replace(author_corrections)

In [22]:
# checking if the corrections were made correctly
books.loc[[642, 634, 500, 476, 1462, 1649, 1650, 1677, 1681], ['title', 'author']]

,title,author
book_id,,
642,العصبي,Ahmed Gamal El-Din Ramadan
634,انتحار فاشل,Ahmed Gamal El-Din Ramadan
500,زندگی مه آلود پریا,Seyyed Morteza Mostafavi
476,القرآن الكريم,Anonymous
1462,Before the Coffee Gets Cold,Toshikazu Kawaguchi
1649,Chto takoe iskusstvo? / What is art?,Leo Tolstoy
1650,Great Dialogues of Plato,Plato
1677,Death's End (The Three-Body Problem Series Boo...,Liu Cixin
1681,The Dark Forest (The Three-Body Problem Series...,Liu Cixin

In [23]:
pd.set_option('display.max_colwidth', None)

In [24]:
# checking the title to be able to know what to correct in the title column
books.loc[[7, 274, 307, 384, 461, 476, 500, 634, 642, 1058, 1120, 1125, 1234, 1333, 1508, 1635], ['title', 'author']]

,title,author
book_id,,
7,J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings,J.R.R. Tolkien
274,"[No Country for Old Men] (By: Cormac McCarthy) [published: December, 2007]",Cormac McCarthy
307,"The Lord of the Rings (The Lord of the Rings, #1-3)",J.R.R. Tolkien
384,Midnight Sun [2008 Draft],Stephenie Meyer
461,’Salem’s Lot,Stephen King
476,القرآن الكريم,Anonymous
500,زندگی مه آلود پریا,Seyyed Morteza Mostafavi
634,انتحار فاشل,Ahmed Gamal El-Din Ramadan
642,العصبي,Ahmed Gamal El-Din Ramadan
1058,"A child called ""it",David J. Pelzer
1120,All She Wanted,"Aphrodite Jones, Ariel Jennifer Jones"
1125,The Mystery of the Blue Train,Agatha Christie
1234,Die Aufzeichnungen des Malte Laurids Brigge,Rainer Maria Rilke
1333,... Trotzdem Ja zum Leben sagen,Viktor E. Frankl
1508,Mein Kampf,Adolf Hitler
1635,Sein und Zeit,Martin Heidegger

In [25]:
# correcting title columns for roman caracters and other corrections
title_corrections = {
    'J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings': 'The Hobbit and The Lord of the Rings',
    '[No Country for Old Men] (By: Cormac McCarthy) [published: December, 2007]': 'No Country for Old Men',
    'Midnight Sun [2008 Draft]': 'Midnight Sun',
    "'Salem's Lot": "Salem's Lot",
    'القرآن الكريم': 'The Holy Quran',
    'زندگی مه آلود پریا': 'Misty Life of Pariya',
    'انتحار فاشل': 'Failed Suicide',
    'العصبي': 'The Nervous One',
    'A child called "it': 'A Child Called It',
    'Die Aufzeichnungen des Malte Laurids Brigge': 'The Notebooks of Malte Laurids Brigge',
    '... Trotzdem Ja zum Leben sagen': "Man's Search for Meaning",
    'Sein und Zeit': 'Being and Time',
}

books['title'] = books['title'].replace(title_corrections)

In [26]:
# checking if the corrections were done
books.loc[[7, 274, 307, 384, 461, 476, 500, 634, 642, 1058, 1120, 1125, 1234, 1333, 1508, 1635], ['title', 'author']]

,title,author
book_id,,
7,The Hobbit and The Lord of the Rings,J.R.R. Tolkien
274,No Country for Old Men,Cormac McCarthy
307,"The Lord of the Rings (The Lord of the Rings, #1-3)",J.R.R. Tolkien
384,Midnight Sun,Stephenie Meyer
461,’Salem’s Lot,Stephen King
476,The Holy Quran,Anonymous
500,Misty Life of Pariya,Seyyed Morteza Mostafavi
634,Failed Suicide,Ahmed Gamal El-Din Ramadan
642,The Nervous One,Ahmed Gamal El-Din Ramadan
1058,A Child Called It,David J. Pelzer
1120,All She Wanted,"Aphrodite Jones, Ariel Jennifer Jones"
1125,The Mystery of the Blue Train,Agatha Christie
1234,The Notebooks of Malte Laurids Brigge,Rainer Maria Rilke
1333,Man's Search for Meaning,Viktor E. Frankl
1508,Mein Kampf,Adolf Hitler
1635,Being and Time,Martin Heidegger

In [27]:
# titeling the title and author columns
books['title'] = books['title'].str.title()
books['author'] = books['author'].str.title()

In [28]:
# cleaning the description column
# removing space before opening quotes
books['description'] = books['description'].str.replace(r'\. "', '."', regex=False)

# removing "Show more" at the end
books['description'] = books['description'].str.replace(r'\s*Show more$', '', regex=True)

# spacing after commas and periods
books['description'] = books['description'].str.replace(r'([.,])(\S)', r'\1 \2', regex=True)

# removing "Alternate cover edition of..." sentences
books['description'] = books['description'].str.replace(r'Alternate cover edition of[^.]*\.?', '', regex=True)

# replacing multiple newlines with a single space
books['description'] = books['description'].str.replace(r'\r\n+', ' ', regex=True)

# cleaning html tags
books['description'] = books['description'].str.replace(r'<[^>]+>', '', regex=True)

In [29]:
# code used to check blocks of descriptions to be able to check if bulk were done and also what needed manual input
books.loc[2002:2003, ['title', 'author', 'year_published', 'description']]

,title,author,year_published,description
book_id,,,,
2002,The Silver Palate Cookbook,"Julee Rosso, Sheila Lukins",1982,"Contains recipes developed by the founders of The Silver Palate gourmet food store in New York, covering all courses from appetizers to desserts, and includes tips on cooking and entertaining."
2003,The Deal / The Mistake / The Score / The Goal / The Legacy,Elle Kennedy,2021,"***The Deal*** Hannah Wells might be confident, but she's carting around a full set of baggage when it comes to sex and seduction. If she wants to get her crush's attention, she'll have to step out of her comfort zone. .. even if it means tutoring the annoying, childish, cocky captain of the hockey team, Garrett Graham, in exchange for a public pretend date. But when one unexpected kiss leads to the wildest sex of their lives, it doesn't take long for Garrett to realize that pretend isn't going to cut it. [***The Deal pdf***](https://chesserresources. com/doc/the-deal-pdf/) ***The Mistake*** For college hockey star John Logan, life is a parade of parties and hook-ups, but behind his killer grins hides growing despair about the dead-end road he'll be forced to walk after graduation. A sexy encounter with freshman Grace Ivers is just the distraction he needs, but when a thoughtless mistake pushes her away, Logan plans to spend his final year proving to her that he's worth a second chance. But this time around, she'll be the one in the driver's seat…and she plans on driving him wild. [***The Mistake pdf***](https://chesserresources. com/doc/the-mistake-by-elle-kennedy-pdf/) ***The Score*** Wild rebound sex after a breakup is definitely not the solution to Allie Hayes's problems, but gorgeous hockey star Dean Di Laurentis is impossible to resist. Just once, though, because even if her future is uncertain, it sure as hell won't include the king of one-night stands. Dean has never met a woman who's immune to his charms…until Allie. For one night, the feisty blonde rocked his entire world―and now she wants to be friends? Nope. It's not over until he says it's over. [***The Score pdf***](https://chesserresources. com/doc/the-score-off-campus-series-book-3-pdf/) ***The Goal*** College senior Sabrina James has her whole future planned out: graduate from college, kick butt in law school, and land a high-paying job at a cutthroat firm. Her path to escaping her shameful past certainly doesn't include a gorgeous hockey player who believes in love at first sight. One night of sizzling heat and surprising tenderness is all she's willing to give John Tucker…but sometimes, one night is all it takes for your entire life to change. [***The Goal pdf***](https://chesserresources. com/doc/the-goal-pdf-2/) ***The Legacy*** Four stories. Four couples. Three years of real life after graduation… A wedding. A proposal. An elopement. And a surprise pregnancy. Can you guess which Off Campus couple is which? [**The Legacy pdf**](https://chesserresources. com/doc/the-legacy-off-campus-series-book-5-pdf/)"

In [30]:
# manual inputing in description column
books.loc[500, 'description'] = "Mystical story. The internal revolution of a woman and the fight against her past. The story follows a successful and charismatic woman who manages a large traditional inn, ranked first in attracting both Iranian and foreign guests. Although Pariya is highly talented and gifted, envied by others for her success, she once made a great mistake in her past that she does not dare reveal to anyone close to her. As the story progresses, her past slowly descends on her restless soul like a nightmare, tormenting her deeply. Falling ill intensifies her guilt, and she faces many challenges in overcoming this crisis."
books.loc[642, 'description'] = "Everyone knew he was nervous. But that was not the problem — the problem was that he admitted it. He acknowledged that he was nervous, easily provoked, and impulsive, yet he never tried to change. Anger would overtake him and he would erupt into a torrent of insults for the most trivial of reasons, sometimes for no reason at all. He would lose his temper"
books.loc[1255, 'description'] = "The Ramayana is one of the greatest Sanskrit epics of ancient India, telling the story of Rama, ideal man and incarnation of the god Vishnu. Written by the sage Valmiki, this monumental work has profoundly shaped the literature, art, religion, and culture of countless millions across South and Southeast Asia for thousands of years. The epic follows Rama's journey through exile, the abduction of his beloved wife Sita by the demon king Ravana, and the great war to rescue her with the help of the monkey hero Hanuman. This scholarly edition, translated by Robert P. Goldman, Rosalind Lefeber, and Sheldon Pollock, is based on the authoritative critical edition and includes extensive introductions, notes, and bibliography."
books.loc[1293, 'description'] = "Published in 1902, As a Man Thinketh is a timeless self-help classic by James Allen that explores the profound connection between thought and reality. Drawing on the biblical aphorism 'As a man thinketh in his heart, so is he,' Allen argues that a person is literally what they think — their character being the complete sum of all their thoughts. Through simple yet powerful insights, Allen shows how cultivating positive, disciplined thinking can transform one's character, circumstances, and destiny. A short but deeply influential work, it has guided millions of readers toward a life of purpose, clarity, and inner peace for over a century."
books.loc[1386, 'description'] = "Published in 1966, The Book: On the Taboo Against Knowing Who You Are is a philosophical masterpiece by Alan Watts that challenges the Western notion of the self as a separate ego isolated from the rest of the universe. Watts argues that this illusion of separateness is at the root of human conflict, our misuse of technology, and our destructive relationship with the natural world. Drawing on the Hindu philosophy of Vedanta, he offers a profound alternative view of personal identity — one in which the self is not separate from, but rather the root and ground of, the universe itself. Written with clarity and wit, this mind-opening book invites readers to question who they really are and to discover a deeper, more harmonious way of existing in the world."
books.loc[1409, 'description'] = "**The Manipulator**  I can manipulate the emotions of anyone who lets me.  I will make you hurt, make you cry, make you laugh and sigh.  But my words don't affect him. Especially not when I plead for him to leave.  He's always there, watching and waiting.  And I can never look away.  Not when I want him to come closer.  **The Shadow**  I didn't mean to fall in love.  But now that I have, I can't stay away.  I'm mesmerized by her smile, by her eyes, and the way she moves.  The way she undresses. . . I'll keep watching and waiting. Until I can make her mine.  And once she is, I'll never let her go.  Not even when she begs me to."
books.loc[1412, 'description'] = """This is the story of Louis, as told in his own words, of his journey through mortal and immortal life. Louis recounts how he became a vampire at the hands of the radiant and sinister Lestat and how he became indoctrinated, unwillingly, into the vampire way of life. His story ebbs and flows through the streets of New Orleans, defining crucial moments such as his discovery of the exquisite lost young child Claudia, wanting not to hurt but to comfort her with the last breaths of humanity he has inside. Yet, he makes Claudia a vampire, trapping her womanly passion, will, and intelligence inside the body of a small child. Louis and Claudia form a seemingly unbreakable alliance and even settle down for a while in the opulent French Quarter. Louis remembers Claudia's struggle to understand herself and the hatred they both have for Lestat that sends them halfway"""
books.loc[1413, 'description'] = "First published in 1928, The Law of Success is Napoleon Hill's landmark motivational masterwork, developed after twenty years of research interviewing America's most successful business leaders. The project began in 1908 when steel baron Andrew Carnegie, impressed by the young Hill during an interview, offered to introduce him to the most powerful men in America so that Hill could distill their secrets into a philosophy anyone could use to achieve success. The result is a comprehensive set of seventeen principles for personal achievement, including The Master Mind, Cooperation, Profiting by Failure, Tolerance, The Golden Rule, and The Universal Law of Cosmic Habitforce. This 75th Anniversary Collector's Edition is the most complete edition ever published, incorporating all seventeen principles and updated with historical context and contemporary stories that illustrate the enduring relevance of Hill's philosophy."
books.loc[1427, 'description'] = "Wise and Otherwise is a collection of fifty poignant vignettes by Sudha Murty, originally written as columns for the New Sunday Express. Drawing from her travels and experiences working with the Infosys"
books.loc[1476, 'description'] = "Into the Heart of Borneo is a rip-roaringly funny travel memoir recounting Redmond O'Hanlon's 1983 expedition to the center of Borneo — a journey no expedition had attempted since 1926. Armed with an SAS survival kit, an impressive library of natural history books, and more optimism than practical skill, O'Hanlon and his companion, the poet James Fenton, set off in search of the legendary and near-extinct Borneo rhinoceros. Guided by three Iban tribesmen — Leon, Dana, and Inghai — the two Oxford academics navigate treacherous river rapids, sweltering jungle, daily leech attacks, and the humbling realization that they are the comic relief of the expedition. Beneath the humor runs a genuine naturalist's wonder at the extraordinary wildlife and tribal cultures of one of the world's most remote and biodiverse places."
books.loc[1478, 'description'] = "The updated and expanded #1 introduction to tourism principles and practices retains its classic approach in this new tenth edition   Virtually every country has taken steps to increase its number of visitors in recent years, and with each new edition, Tourism has remained the must-have resource dedicated to providing an exciting, comprehensive introduction to the world's most rapidly growing industry. This Tenth Edition explores new trends in travel and tourism, while continuing the book's long-standing tradition of taking a global look into the economic, political, and social forces that drive and shape tourism."
books.loc[1481, 'description'] = "Winner of the Hugo and Nebula Awards for Best Novella, Binti is an Afrofuturist science fiction story by Nnedi Okorafor. Binti is a young woman of the Himba people of Namibia — a traditional, insular community that rarely leaves their homeland. When she is accepted to the prestigious interstellar Oomza University, she secretly leaves her family behind, becoming the first of her people to make the journey. But everything changes when the jellyfish-like Medusae attack her spaceship, leaving her the only survivor. Alone on a ship full of the beings who murdered her crew, Binti must draw on her extraordinary gift for mathematics, her cultural heritage, and her courage to negotiate peace between two ancient enemies. A powerful and moving novella about identity, belonging, and the courage to bridge worlds."
books.loc[1512, 'description'] = "This volume brings together two of George Orwell's most celebrated works of political fiction. In Animal Farm, a group of overworked farm animals overthrow their human master and set out to build a fair and equal society. But as the pigs gradually seize control, their revolutionary ideals are corrupted into a tyranny as brutal as the one they replaced — a razor-sharp satire on the nature of power and revolution. In Nineteen Eighty-Four, Winston Smith lives in a totalitarian future where Big Brother watches every move and the Thought Police can read every mind. Working at the Ministry of Truth, Winston secretly rebels against the Party, beginning a dangerous love affair and searching for a way to resist. Together, these two masterpieces remain among the most urgent and enduring warnings about totalitarianism, propaganda, and the fragility of freedom ever written."
books.loc[1534, 'description'] = "We the People is the leading introductory textbook on American government, widely used in university courses across the United States. Written by a team of distinguished political scientists, it explains how the American political system works, why it matters, and how ordinary citizens can engage with and influence it. The book covers the foundations of American democracy, the Constitution, Congress, the presidency, the judiciary, political parties, elections, civil liberties, and public policy. A key feature of the text is its emphasis on civic participation — using real stories of everyday Americans to show how government decisions affect people's lives and why political engagement matters. With its signature features such as Who Are Americans? and Who Participates?, the book encourages critical thinking about representation, inequality, and democracy in practice."
books.loc[1539, 'description'] = "The Price of My Soul is the autobiography of Bernadette Devlin, written when she was just 22 years old and already the youngest woman ever elected to the British Parliament. Growing up in poverty in Northern Ireland, Devlin traces her journey from a rebellious schoolgirl to one of the most prominent voices of the civil rights movement of the 1960s. She recounts her family's struggle with bottom-level poverty, her fight to attend university while caring for her orphaned siblings, and her rise as a leader of the protests that brought Northern Ireland to the world's attention in 1968 and 1969. Devlin argues that the conflict in Northern Ireland was not simply a sectarian divide between Catholics and Protestants, but fundamentally a struggle rooted in economic inequality and class oppression. Raw, honest, and fiercely political, this memoir is an essential account of one woman's fight for justice and civil rights."
books.loc[1574, 'description'] = "Man and Superman is a four-act comedy by George Bernard Shaw, written in 1903 in response to a request from his friend and theatre critic Arthur Bingham Walkley, who had asked why Shaw had never written a Don Juan play. Shaw obliged by reimagining the legend through the lens of his own philosophy. The play follows John Tanner, a passionate radical and self-declared revolutionary, who is relentlessly pursued by the determined Ann Whitefield despite his resistance to marriage and domesticity. At its philosophical heart is Act III, Don Juan in Hell, a brilliant debate between Don Juan, the Devil, Dona Ana, and the Statue on the nature of life, love, and the evolution of humanity toward the Superman — Nietzsche's ideal of a higher human being. A sharp, witty satire of Victorian society, gender roles, and the hypocrisy of conventional morality, Man and Superman is widely considered the first great twentieth-century English play."
books.loc[1575, 'description'] = "Constitutional and Administrative Law is a leading textbook on UK public law by Hilaire Barnett, former Senior Lecturer in Law at Queen Mary, University of London. Trusted by generations of law students, it provides reliable, accessible, and comprehensive coverage of the public law syllabus. The book equips students with a thorough understanding of the UK constitution's past, present, and future by analysing the political and socio-historical contexts that have shaped the major rules and principles of constitutional and administrative law, including parliamentary sovereignty, the rule of law, devolution, judicial review, human rights, and ongoing constitutional reform. Written in a clear and accessible style, it is an indispensable guide for anyone studying public law for the first time."
books.loc[1584, 'description'] = "Principles of Political Science is a foundational textbook on political theory by Filipino legal scholar and statesman José Maminta Aruego, first published in 1947 and widely used in Philippine universities for decades. The book covers the essential concepts of political science, beginning with the nature and scope of the discipline and its methods of inquiry. It examines the state — its definition, elements, origins, and forms — alongside the fundamental principles of government, sovereignty, constitutional law, and international relations. Grounded in both Western political thought and the Philippine context, the book remains an important reference for students of political science and public law in the Philippines."
books.loc[1599, 'description'] = "Published in 1951, The Wisdom of Insecurity is Alan Watts' timeless philosophical guide to finding peace in an age of anxiety. Drawing on Eastern philosophy — particularly Zen Buddhism and Taoism — Watts argues that much of our psychological suffering stems from a futile attempt to achieve security in a constantly changing and impermanent world. When we spend our lives worrying about the future and lamenting the past, we are unable to inhabit the only moment that truly exists: the present. His central and paradoxical insight is that true certitude and security come only from embracing impermanence and letting go of the illusion of control. Written in clear, accessible prose, The Wisdom of Insecurity remains one of Watts' most beloved and enduring works, as relevant today as when it was first published."
books.loc[1678, 'description'] = "What happens when you plant just one little bean? One Bean is a charming children's science picture book that takes young readers step-by-step through the complete life cycle of a plant. Starting with a single dry bean, a young narrator soaks it, plants it in a paper cup, waters it, watches it sprout, repots it, and eventually harvests and eats the beans it produces. Illustrated with cheerful three-dimensional paper sculptures by Megan Halsey, the book is an accessible and joyful introduction to plant growth and scientific observation, perfect for preschool and early elementary readers. Three bonus bean activities and information for adults are included at the back."
books.loc[1716, 'description'] = "Robots and Empire is the fifth novel in Isaac Asimov's Robot Series and a landmark work in his broader science fiction universe, serving as the thrilling continuation of The Robots of Dawn. The future of the universe is in danger. Although the power of the sinister Spacers has weakened, Dr. Kelden Amadiro has neither forgotten nor forgiven his humiliating defeat at the hands of Elijah Baley, the beloved hero of Earth's population. Amadiro craves revenge and is more determined than ever to bring about the destruction of planet Earth. It is up to the robots Daneel and Giskard to uncover the plot and protect humanity — setting in motion events that will shape the entire future of the galaxy and bridge the gap between Asimov's Robot and Foundation series."
books.loc[1755, 'description'] = "Prelude to Foundation is the first chronological novel in Isaac Asimov's legendary Foundation series. Set on the planet Trantor, capital of the Galactic Empire, it follows the young mathematician Hari Seldon on the day he presents a paper on psychohistory — a theoretical mathematics capable of predicting the future of civilizations. What begins as pure theory soon attracts dangerous attention from those who wish to control or suppress such power. Forced to flee across the vast and labyrinthine city-planet of Trantor, Seldon embarks on a journey that will transform psychohistory from an abstract idea into the foundation of his life's work. Both an ideal entry point for new readers and a rich origin story for fans of the series, Prelude to Foundation is one of the great masterworks of contemporary science fiction."
books.loc[1765, 'description'] = "Ars Amatoria, or The Art of Love, is a witty and audacious didactic poem in three books by the ancient Roman poet Ovid, written around 2 AD. The first two books are addressed to men, offering playful and practical advice on how to find, win, and keep a woman's love — covering everything from where to meet women in Rome to how to write a flattering letter. The third book turns to women, advising them on how to attract and hold the attention of a man. Rich with humor, psychological insight, and vivid glimpses of Roman social life — the theatre, the circus, the banquet — the poem is one of the wittiest works of Latin literature. Its irreverent tone so scandalized Emperor Augustus that it was cited as one of the reasons for Ovid's eventual banishment from Rome."
books.loc[1780, 'description'] = "One L is Scott Turow's acclaimed memoir of his first year at Harvard Law School, first published in 1977 and based on a diary he kept throughout the experience. Known as a One L — the term for first-year law students — Turow takes readers inside the oldest and most prestigious law school in the country, vividly portraying the intellectual and emotional ordeal of that grueling year. From the notorious Socratic method to the crushing workload, fierce competition, and moral dilemmas that test his character, Turow captures the humiliations and triumphs of becoming a lawyer with candor and insight. A national bestseller, a law school primer, and a classic autobiography, One L is essential reading for anyone who has ever contemplated going to law school — and for anyone interested in the human cost of ambition."
books.loc[1811, 'description'] = "Entrepreneurship by Robert D. Hisrich is a leading university textbook designed to clearly instruct students on the process of formulating, planning, and implementing a new venture. Students are exposed to detailed, practical guidance on how to embark on a new business in a logical and structured manner, covering topics such as identifying opportunities, developing a business plan, securing funding, managing growth, and navigating the challenges of today's entrepreneurial landscape. Drawing on Hisrich's extensive expertise in global entrepreneurship, the book balances theory with real-world application, making it an essential resource for anyone studying or pursuing entrepreneurship."
books.loc[1812, 'description'] = "The Constitution of India, adopted on 26 November 1949 and effective from 26 January 1950, is the supreme law of India and one of the longest written constitutions in the world. It establishes the framework for the country's political system, defining the structure, powers, and duties of the government at the central and state levels. The Constitution guarantees fundamental rights to all citizens, outlines directive principles of state policy, and sets out the duties of citizens. It provides for a parliamentary form of government, an independent judiciary, and a federal structure with a strong central government. As a living document, it has been amended by Parliament numerous times to reflect the evolving needs of Indian society and governance."
books.loc[1842, 'description'] ="It was the perfect crime. . . almost.  For Salt Lake City resident and respected community member David Meade, there was only one way out of a miserable marriage and financial ruin: cold-blooded murder."
books.loc[1858, 'description'] = "Economics: An Introductory Analysis by Paul A. Samuelson and William D. Nordhaus is one of the most influential and bestselling economics textbooks ever written. First published in 1948 by Nobel Prize-winning economist Paul Samuelson, it set the gold standard for introductory economics education and introduced Keynesian macroeconomics to generations of students. Translated into 41 languages and selling over four million copies, it has appeared in nineteen editions and remains a standard-bearer in economics courses worldwide. The book covers the full spectrum of economic theory — including microeconomics, macroeconomics, supply and demand, market structures, trade, economic growth, and monetary policy — with clear explanations, compelling examples, and a commitment to helping students understand enduring economic principles and apply them to the real world."
books.loc[1865, 'description'] = "Business Law Today is a leading university textbook by Roger LeRoy Miller and Gaylord A. Jentz, designed to make business law engaging, accessible, and relevant to students. Clear, interesting, and applied, it serves as an ideal guide to the law and what it means in the business world — covering topics from contracts, secured transactions, and warranties to government regulations, intellectual property, e-commerce, and global business law. Each chapter uses real-world cases and visually engaging learning tools to illustrate how law applies to actual business problems, and how landmark statutes and court decisions shape the way businesses operate in the United States and internationally. A widely adopted textbook in business law and legal environment courses, it balances legal credibility with practical, student-friendly coverage."
books.loc[1878, 'description'] = "Microeconomic Theory: Basic Principles and Extensions by Walter Nicholson and Christopher Snyder is a market-leading textbook widely known as the bible of microeconomics for upper-level undergraduate and beginning graduate students. Taking a calculus-based approach, the book provides an ideal level of mathematical rigor while remaining accessible and practical. It covers the full spectrum of microeconomic theory — including consumer choice and demand, uncertainty, game theory, production and cost functions, competitive markets, market power, monopoly, pricing in input markets, and market failure — with clear explanations, insightful graphics, and real-world applications. Two-tier end-of-chapter problems build students' intuition progressively, from simple numerical exercises to complex analytical and behavioral economics challenges. Rigorous yet engaging, it is an essential resource for anyone studying advanced microeconomics."
books.loc[1928, 'description'] = "Planning, Implementing, and Evaluating Health Promotion Programs: A Primer by James F. McKenzie, Brad L. Neiger, and Rosemary Thackeray is the leading textbook for undergraduate courses in health education, promotion, and program planning. The first book to combine all three phases — planning, implementation, and evaluation — in one comprehensive volume, it provides students with both the practical and theoretical skills needed to develop effective health promotion programs across a variety of settings. Using a clear, step-by-step format, the book covers needs assessment, program planning models, health behavior theory, social marketing, program management, evaluation methods, and professional ethics. Updated throughout to reflect the latest national standards and Healthy People objectives, it is an essential resource for students and professionals in public health and health education."
books.loc[1931, 'description'] = "A study guide providing a comprehensive overview and analysis of Erving Goffman's foundational work on social interaction and the presentation of self in everyday life."
books.loc[1941, 'description'] = "The Power of Color: Creating Healthy Interior Spaces is the first practical guide to using full-spectrum color in interior design to support human health and well-being. Working from the scientifically based premise that color on finishes and surfaces plays a vital role in creating healthy environments, Sara O. Marberry and Laurie Zagon provide design professionals with a complete methodology and clear guidelines for designing with color without compromising style or client preferences. The book includes a concise refresher course in color theory, detailed analyses of over 20 real-world projects across healthcare facilities, schools, day-care centers, hotels, and offices, color charts breaking down proportions of hue, value, and chroma, and a showcase of over 40 full-color photographs illustrating the concepts in practice."
books.loc[1943, 'description'] = "The Social Construction of Reality: A Treatise in the Sociology of Knowledge is a landmark 1966 work by sociologists Peter L. Berger and Thomas Luckmann, voted the fifth most important sociological book of the twentieth century by the International Sociological Association. The book introduces the concept of social construction into the social sciences, arguing that reality as we experience it is not objectively given but is actively created through human interaction and habitualization. Over time, repeated patterns of interaction become institutionalized and are passed on to future generations as objective reality — a process the authors call reification. Drawing on the phenomenological tradition, Berger and Luckmann reformulate the sociology of knowledge to show how society is simultaneously a human product and an objective reality that shapes the very humans who created it. An essential text in sociology, philosophy, and social theory."
books.loc[1964, 'description'] = "Cunningham's Encyclopedia of Magical Herbs is the definitive reference guide to the magical uses of over 400 herbs and plants from around the world, written by one of the most beloved authors in modern Wicca and earth magic, Scott Cunningham. Each entry includes the herb's common and folk names, associated magical properties, ruling planet and element, and practical uses in spells, rituals, and natural magic. Illustrated for easy identification and organized for quick reference, this comprehensive encyclopedia has sold over 400,000 copies and remains an essential resource for anyone practicing natural, herbal, or folk magic."
books.loc[1965, 'description'] = "First published in 1903, Le Guide Culinaire is Auguste Escoffier's monumental masterwork and one of the most influential cookbooks ever written. Described by Escoffier himself as a useful tool rather than just a recipe book, it contains over 5,000 recipes covering the full spectrum of classical French cuisine — from fundamental stocks and mother sauces to soups, fish, meats, poultry, vegetables, and desserts. Written for professional chefs and culinary students, it does not dwell on minute preparation details but instead offers invaluable guidelines distilled from over fifty years of experience in the grandest kitchens of Europe, including the Savoy and Carlton hotels in London. Still used as a textbook in culinary schools worldwide, Le Guide Culinaire remains the definitive reference for classical French and international haute cuisine."
books.loc[1983, 'description'] = "Winner of the James Beard Award for General Cooking and the IACP Cookbook of the Year, The Food Lab: Better Home Cooking Through Science is J. Kenji Lopez-Alt's landmark 960-page culinary masterwork, with over one million copies sold. As the culinary director of Serious Eats, Kenji approaches cooking as a science — questioning conventional wisdom, designing kitchen experiments, and finding the best, most efficient techniques for making great food at home. The book focuses on the science behind beloved American dishes, exploring the interactions between heat, energy, and molecules that produce delicious results. With nearly 300 recipes and over 1,000 full-color photographs, it covers everything from foolproof steaks and crispy fried chicken to homemade mac and cheese and roast turkey. Called The Joy of Cooking for the modern cook by USA Today, it is an indispensable resource for anyone who wants to understand not just how to cook, but why."
books.loc[1992, 'description'] = "Tender at the Bone is the warmly funny and vividly written food memoir by Ruth Reichl, one of America's most celebrated food critics and former editor of Gourmet magazine. Growing up with a mother who was a legendarily reckless cook — nicknamed the Queen of Mold for her cheerful disregard for food safety — Reichl discovered early that food was a way of making sense of the world, and that watching people eat revealed who they truly were. The book follows her journey from a chaotic New York childhood through her young adulthood, tracing her culinary education through a cast of unforgettable characters — a Baltimore socialite turned unlikely maid, a French gourmand who marveled at a child's first souffle, and the organic food revolutionaries of 1970s Berkeley. Part coming-of-age story, part love letter to the pleasures of the table, Tender at the Bone is a memoir about how food shapes not just meals but memory, identity, and the people we become."
books.loc[2002, 'description'] = "The Silver Palate Cookbook is the groundbreaking cookbook that changed the way Americans cook and entertain. Created by Julee Rosso and Sheila Lukins, founders of the legendary Silver Palate gourmet food shop on Manhattan's Upper West Side, the book introduced a generation of home cooks to bold flavors, fresh ingredients, and a relaxed, generous approach to cooking and hosting. Covering everything from appetizers and soups to main courses, salads, and show-stopping desserts, it combines approachable recipes with witty commentary, beautiful illustrations, and practical tips for effortless entertaining. With over 2.5 million copies sold since its publication in 1982, The Silver Palate Cookbook remains a beloved classic that helped launch America's gourmet food revolution."
books.loc[2003, 'description'] = "The Off Campus series by Elle Kennedy is a wildly popular collection of New Adult sports romances set in the world of college hockey. The Deal follows good-girl Hannah and cocky hockey captain Garrett, whose fake dating arrangement leads to very real feelings. The Mistake centers on charming player John Logan, who must win back the one girl who saw through his smile. The Score pairs wild-child Dean with sharp-tongued Allie in a battle of wills that neither can win alone. The Goal follows driven pre-law student Sabrina, whose carefully mapped future is upended by one unexpected night with hockey star Tucker. The Legacy revisits all four couples three years after graduation, catching up with weddings, proposals, elopements, and surprises. Addictive, funny, and steamy, the series is beloved for its sharp banter, lovable characters, and the perfect balance of heat and heart."

In [31]:
# author check for the full data set (in blocks) to clean and take out duplicated names in the column (per row)
books.loc[1901:2003, ['title', 'author']]

,title,author
book_id,,
1901,Tom'S Midnight Garden,Philippa Pearce
1902,Thinking In Systems,"Donella H. Meadows, Diana Wright"
1903,The Power Of Productivity,William W. Lewis
1904,How Not To Die,"Michael Greger, Gene Stone"
1905,How To Make Money In Stocks,William J. O'Neil
1906,Bad Blood,John Carreyrou
1907,Techno-Feudalism,Yanis Varoufakis
1908,Principles Of Political Economy,John Stuart Mill
1909,Expecting Better,Emily Oster
1910,The Economic Consequences Of The Peace (Twentieth-Century Classics),"John Maynard Keynes, Jens Hölscher, Matthias Klaes, Anonymous"
1911,The Power Of Now,Eckhart Tolle
1912,The Global Business Environment,Janet Morrison
1913,Leadership And Self Deception,"The Arbinger Institute, Dick Ruhe"
1914,Business Forecasting,"John E. Hanke, Dean Wichern"
1915,Sacred Woman,"Queen Afua, Afua Queen."
1916,Operations Management,William J. Stevenson
1917,Effective Executive,"Peter F. Drucker, Joseph A. Maciariello, Jim Collins, Tim Andres Pabon, Zachary First"
1918,How To Keep House While Drowning,Kc Davis
1919,Integrated Principles Of Zoology,Cleveland P. Hickman
1920,"Ageless Body, Timeless Mind",Deepak Chopra
1921,"Fields, Factories, And Workshops",Peter Kropotkin
1922,Weslandia,Paul Fleischman
1923,Health Behavior,"Karen Glanz, Barbara K. Rimer, K. Viswanath"
1924,Food Rules,"Michael Pollan, Laura Manero Jiménez;"
1925,Capitalism And Freedom,Milton Friedman
1926,The Art Of Strategy,"Avinash K. Dixit, Barry J. Nalebuff, Matthew Dudley"
1927,Wonder,R. J. Palacio
1928,"Planning, Implementing, And Evaluating Health Promotion Programs","James F. Mckenzie, Brad L. Neiger, Rosemary Thackeray"
1929,Caffeine Blues,Stephen Snehan Cherniske
1930,Understanding The Borderline Mother,Christine Ann Lawson
1931,Study Guide,Supersummary
1932,How To Not Die Alone,"Logan Ury, Genis Monrabà"
1933,Mental Health Through Will-Training,Abraham A. Low
1934,If You Tell,Gregg Olsen
1935,The Herbal Drugstore,"Linda B. White, Steven Foster, Herbs For Health Staff"
1936,The Varieties Of Religious Experience,"William James, Dr. William James, William James, James, William, William James, Crossreach Publications"
1937,Hope And Help For Your Nerves,Claire Weekes
1938,L'Imagination Sociologique,C. Wright Mills
1939,The Greek Tycoon'S Disobedient Bride,Lynne Graham
1940,The Book You Wish Your Parents Had Read,Philippa Perry
1941,The Power Of Color,"Sara O. Marberry, Laurie Zagon"
1942,When God Was A Woman,Merlin Stone
1943,The Social Construction Of Reality,"Peter L. Berger, Thomas Luckmann, David Colacci, Berger, Peter L., Luckmann, Thomas A."
1944,Raising Good Humans,"Hunter Clarke-Fields Msae, Carla Naumburg Phd"
1945,The Golden Bough,James George Frazer
1946,Democracy And Education,John Dewey
1947,The Art Of Self-Directed Learning,Blake Boles
1948,The Secret Of Childhood,Maria Montessori
1949,Orthodoxy,Gilbert Keith Chesterton
1950,Natural Law In The Spiritual World,Henry Drummond
1951,Make It Stick,"Peter C. Brown, Henry L. Roediger, Mark A. Mcdaniel"
1952,Deschooling Society,Ivan Illich
1953,The Absorbent Mind,Maria Montessori
1954,This Is Water,David Foster Wallace
1955,Zodiac,Robert Graysmith
1956,The Mis-Education Of The Negro,"Carter Godwin Woodson, George G.M. James"
1957,Indian Sociological Thought,B. K. Nagla
1958,How To Cook Everything,Mark Bittman
1959,Boston Cooking-School Cook Book,"Fannie Merritt Farmer, Lincoln, Mary Johnson Bailey ""Mrs. D. A. Lincoln,"", James B. Herndon , Herndon/Vehling Collection, Sam Sloan, D. A. Lincoln"
1960,Joy Of Cooking,"Irma S. Rombauer, Marion Rombauer Becker, Ethan Becker, John Becker, Megan Scott"
1961,"Salt, Fat, Acid, Heat",Samin Nosrat
1962,White Heat,Marco Pierre White
1963,Odd Thomas,Dean Koontz
1964,Cunningham'S Encyclopedia Of Magical Herbs,"Scott Cunningham, Llewellyn Publications"
1965,Guide Culinaire,"Auguste Escoffier, Christian Constant, Herndon/Vehling Collection Fmo, Anonymous"
1966,A Book Of Mediterranean Food,Elizabeth David
1967,Cooking Basics For Dummies,"Bryan Miller, Marie Rama"
1968,The Professional Chef,"Culinary Institute Of America., The Culinary Institute Of America (Cia), Elizabeth Riely, Steven Kolpan, Linda Blocker, Culinary Institute Of America (Cia) Staff, Nra Educational Foundation, Le Roi A. Folsom"
1969,Betty Crocker Cookbook,Betty Crocker
1970,How To Be A Domestic Goddess,Nigella Lawson
1971,Odd Hours,Dean Koontz
1972,French Country Cooking (Cookery Library),"Elizabeth David, John Minton"
1973,Mastering The Art Of French Cooking,Julia Child
1974,Panaderia Y Reposteria Para Profesionales/Professional Baking,"Wayne Gisslen, W Gisslen, Wayne Gisslen"
1975,The I Hate To Cook Book,Peg Bracken
1976,"French Chef Cookbook, The",Julia Child
1977,New York Times Cook Book,Craig Claiborne
1978,French Provincial Cooking,Elizabeth David
1979,The Flavor Bible,Karen Page
1980,Original White House Cookbook,"Hugo Ziemann, F. L. Gillette, Hugo Zimmerman, Mrs Gillette"
1981,Ma Cuisine,Auguste Escoffier
1982,Frugal Housewife,Lydia Maria Child
1983,The Food Lab,J. Kenji López-Alt
1984,A Gentle Awakening,Betty Neels
1985,Let'S Cook It Right.,Adelle Davis
1986,Julie And Julia,Julie Powell
1987,The Fannie Farmer Cookbook,Marion Cunningham
1988,Flour Water Salt Yeast,Ken Forkish
1989,The Nancy Drew Cookbook,Carolyn Keene
1990,A Bird In The Hand,Ann Cleeves
1991,Knave Of Hearts,Stacy Absalom
1992,Tender At The Bone,Ruth Reichl
1993,Home Cooking,Laurie Colwin
1994,Consider The Fork,Bee Wilson
1995,My Life In France,Julia Child
1996,How To Cook Everything - The Basics,Mark Bittman
1997,Nourishing Traditions,Sally Fallon
1998,Heat,Bill Buford
1999,The Art Of Eating,M. F. K. Fisher
2000,The Fireside Cook Book,"James Beard, Alice Provensen, Martin Provensen, Mark Bittman"
2001,The Little House Cookbook,Barbara M. Walker
2002,The Silver Palate Cookbook,"Julee Rosso, Sheila Lukins"
2003,The Deal / The Mistake / The Score / The Goal / The Legacy,Elle Kennedy

In [32]:
# cleaning the author columns
# remove HTML non-breaking spaces
books['author'] = books['author'].str.replace(r'&nbsp;', ' ', regex=False)

# collapse multiple spaces into one
books['author'] = books['author'].str.replace(r' +', ' ', regex=True)

# strip leading/trailing spaces
books['author'] = books['author'].str.strip()

In [33]:
# clenaing author column after mannual review
books.loc[1031, 'author'] = "Malala Yousafzai, Christina Lamb"
books.loc[1034, 'author'] = "M. H. Abrams, Stephen Greenblatt"
books.loc[1043, 'author'] = "Charlotte Perkins Gilman"
books.loc[1060, 'author'] = "Jon Wiles, Joseph Bondi"
books.loc[1108, 'author'] = "Elizabeth Kendall"
books.loc[1133, 'author'] = "John Taylor Gatto"
books.loc[1163, 'author'] = "Martin Puchner, Suzanne Conklin Akbari, Wiebke Denecke, Barbara Fuchs, Caroline Levine, Pericles Lewis, Emily Wilson"
books.loc[1173, 'author'] = "M. David Miller, Robert L. Linn, Norman E. Gronlund"
books.loc[1199, 'author'] = "R. R. Palmer, Joel G. Colton"
books.loc[1208, 'author'] = "Winston S. Churchill"
books.loc[1209, 'author'] = "H. W. Janson, Anthony F. Janson"
books.loc[1211, 'author'] = "Jerry H. Bentley, Herbert F. Ziegler"
books.loc[1241, 'author'] = "Chancellor Williams"
books.loc[1244, 'author'] = "Anonymous"
books.loc[1250, 'author'] = "Ibn Khaldun"
books.loc[1290, 'author'] = "Robert A. Glover"
books.loc[1309, 'author'] = "James A. Banks, Cherry A. McGee Banks"
books.loc[1336, 'author'] = "Tim Grover, Shari Wenk"
books.loc[1345, 'author'] = "Fumio Sasaki"
books.loc[1351, 'author'] = "Marshall B. Rosenberg"
books.loc[1388, 'author'] = "Matthew McKay, Patrick Fanning"
books.loc[1526, 'author'] = "Thomas Paine"
books.loc[1555, 'author'] = "Mutesa II Kabaka of Buganda"
books.loc[1558, 'author'] = "Philip K. Dick"
books.loc[1559, 'author'] = "Malika Oufkir"
books.loc[1570, 'author'] = "Edward S. Herman, Noam Chomsky"
books.loc[1619, 'author'] = "Ludwig Wittgenstein"
books.loc[1620, 'author'] = "Michael Pollan"
books.loc[1663, 'author'] = "George Lakoff, Mark Johnson"
books.loc[1725, 'author'] = "Gerard J. Tortora, Bryan H. Derrickson"
books.loc[1743, 'author'] = "Robert Silverberg, Robert A. Heinlein, Arthur C. Clarke, Isaac Asimov, Ray Bradbury"
books.loc[1765, 'author'] = "Ovid, Len Krisak, Sarah Ruden"
books.loc[1778, 'author'] = "John E. Douglas, Mark Olshaker"
books.loc[1799, 'author'] = "Robert W. Mann, Miryam Williamson"
books.loc[1809, 'author'] = "John Dickie"
books.loc[1815, 'author'] = "Walter Kirn"
books.loc[1820, 'author'] = "Robert W. Newsom III, William Trotter"
books.loc[1851, 'author'] = "Walter Rodney"
books.loc[1856, 'author'] = "Thomas Aquinas"
books.loc[1857, 'author'] = "Robert S. Pindyck, Daniel L. Rubinfeld"
books.loc[1858, 'author'] = "Paul A. Samuelson, William D. Nordhaus"
books.loc[1859, 'author'] = "Kerry Patterson, Joseph Grenny, Ron McMilIan, Al Switzler"
books.loc[1863, 'author'] = "Jim Collins, Jerry I. Porras"
books.loc[1865, 'author'] = "Roger LeRoy Miller, Gaylord A. Jentz"
books.loc[1885, 'author'] = "J. C. Smith, Brian Hogan"
books.loc[1888, 'author'] = "Anonymous"
books.loc[1910, 'author'] = "John Maynard Keynes"
books.loc[1915, 'author'] = "Queen Afua"
books.loc[1931, 'author'] = "Supersummary"
books.loc[1935, 'author'] = "Linda B. White, Steven Foster"
books.loc[1936, 'author'] = "William James"
books.loc[1943, 'author'] = "Peter L. Berger, Thomas Luckmann"
books.loc[1959, 'author'] = "Fannie Merritt Farmer"
books.loc[1964, 'author'] = "Scott Cunningham"
books.loc[1965, 'author'] = "Auguste Escoffier"
books.loc[1968, 'author'] = "The Culinary Institute Of America"
books.loc[1974, 'author'] = "Wayne Gisslen"
books.loc[1980, 'author'] = "Hugo Ziemann, F. L. Gillette"

In [34]:
# title check for the full data set (in blocks) to clean any typos or anything that is not consistent with the original title of the book
books.loc[1900:2003, ['title', 'author']]

,title,author
book_id,,
1900,Fitness For Dummies,"Suzanne Schlosberg, Liz Neporent"
1901,Tom'S Midnight Garden,Philippa Pearce
1902,Thinking In Systems,"Donella H. Meadows, Diana Wright"
1903,The Power Of Productivity,William W. Lewis
1904,How Not To Die,"Michael Greger, Gene Stone"
1905,How To Make Money In Stocks,William J. O'Neil
1906,Bad Blood,John Carreyrou
1907,Techno-Feudalism,Yanis Varoufakis
1908,Principles Of Political Economy,John Stuart Mill
1909,Expecting Better,Emily Oster
1910,The Economic Consequences Of The Peace (Twentieth-Century Classics),John Maynard Keynes
1911,The Power Of Now,Eckhart Tolle
1912,The Global Business Environment,Janet Morrison
1913,Leadership And Self Deception,"The Arbinger Institute, Dick Ruhe"
1914,Business Forecasting,"John E. Hanke, Dean Wichern"
1915,Sacred Woman,Queen Afua
1916,Operations Management,William J. Stevenson
1917,Effective Executive,"Peter F. Drucker, Joseph A. Maciariello, Jim Collins, Tim Andres Pabon, Zachary First"
1918,How To Keep House While Drowning,Kc Davis
1919,Integrated Principles Of Zoology,Cleveland P. Hickman
1920,"Ageless Body, Timeless Mind",Deepak Chopra
1921,"Fields, Factories, And Workshops",Peter Kropotkin
1922,Weslandia,Paul Fleischman
1923,Health Behavior,"Karen Glanz, Barbara K. Rimer, K. Viswanath"
1924,Food Rules,"Michael Pollan, Laura Manero Jiménez;"
1925,Capitalism And Freedom,Milton Friedman
1926,The Art Of Strategy,"Avinash K. Dixit, Barry J. Nalebuff, Matthew Dudley"
1927,Wonder,R. J. Palacio
1928,"Planning, Implementing, And Evaluating Health Promotion Programs","James F. Mckenzie, Brad L. Neiger, Rosemary Thackeray"
1929,Caffeine Blues,Stephen Snehan Cherniske
1930,Understanding The Borderline Mother,Christine Ann Lawson
1931,Study Guide,Supersummary
1932,How To Not Die Alone,"Logan Ury, Genis Monrabà"
1933,Mental Health Through Will-Training,Abraham A. Low
1934,If You Tell,Gregg Olsen
1935,The Herbal Drugstore,"Linda B. White, Steven Foster"
1936,The Varieties Of Religious Experience,William James
1937,Hope And Help For Your Nerves,Claire Weekes
1938,L'Imagination Sociologique,C. Wright Mills
1939,The Greek Tycoon'S Disobedient Bride,Lynne Graham
1940,The Book You Wish Your Parents Had Read,Philippa Perry
1941,The Power Of Color,"Sara O. Marberry, Laurie Zagon"
1942,When God Was A Woman,Merlin Stone
1943,The Social Construction Of Reality,"Peter L. Berger, Thomas Luckmann"
1944,Raising Good Humans,"Hunter Clarke-Fields Msae, Carla Naumburg Phd"
1945,The Golden Bough,James George Frazer
1946,Democracy And Education,John Dewey
1947,The Art Of Self-Directed Learning,Blake Boles
1948,The Secret Of Childhood,Maria Montessori
1949,Orthodoxy,Gilbert Keith Chesterton
1950,Natural Law In The Spiritual World,Henry Drummond
1951,Make It Stick,"Peter C. Brown, Henry L. Roediger, Mark A. Mcdaniel"
1952,Deschooling Society,Ivan Illich
1953,The Absorbent Mind,Maria Montessori
1954,This Is Water,David Foster Wallace
1955,Zodiac,Robert Graysmith
1956,The Mis-Education Of The Negro,"Carter Godwin Woodson, George G.M. James"
1957,Indian Sociological Thought,B. K. Nagla
1958,How To Cook Everything,Mark Bittman
1959,Boston Cooking-School Cook Book,Fannie Merritt Farmer
1960,Joy Of Cooking,"Irma S. Rombauer, Marion Rombauer Becker, Ethan Becker, John Becker, Megan Scott"
1961,"Salt, Fat, Acid, Heat",Samin Nosrat
1962,White Heat,Marco Pierre White
1963,Odd Thomas,Dean Koontz
1964,Cunningham'S Encyclopedia Of Magical Herbs,Scott Cunningham
1965,Guide Culinaire,Auguste Escoffier
1966,A Book Of Mediterranean Food,Elizabeth David
1967,Cooking Basics For Dummies,"Bryan Miller, Marie Rama"
1968,The Professional Chef,The Culinary Institute Of America
1969,Betty Crocker Cookbook,Betty Crocker
1970,How To Be A Domestic Goddess,Nigella Lawson
1971,Odd Hours,Dean Koontz
1972,French Country Cooking (Cookery Library),"Elizabeth David, John Minton"
1973,Mastering The Art Of French Cooking,Julia Child
1974,Panaderia Y Reposteria Para Profesionales/Professional Baking,Wayne Gisslen
1975,The I Hate To Cook Book,Peg Bracken
1976,"French Chef Cookbook, The",Julia Child
1977,New York Times Cook Book,Craig Claiborne
1978,French Provincial Cooking,Elizabeth David
1979,The Flavor Bible,Karen Page
1980,Original White House Cookbook,"Hugo Ziemann, F. L. Gillette"
1981,Ma Cuisine,Auguste Escoffier
1982,Frugal Housewife,Lydia Maria Child
1983,The Food Lab,J. Kenji López-Alt
1984,A Gentle Awakening,Betty Neels
1985,Let'S Cook It Right.,Adelle Davis
1986,Julie And Julia,Julie Powell
1987,The Fannie Farmer Cookbook,Marion Cunningham
1988,Flour Water Salt Yeast,Ken Forkish
1989,The Nancy Drew Cookbook,Carolyn Keene
1990,A Bird In The Hand,Ann Cleeves
1991,Knave Of Hearts,Stacy Absalom
1992,Tender At The Bone,Ruth Reichl
1993,Home Cooking,Laurie Colwin
1994,Consider The Fork,Bee Wilson
1995,My Life In France,Julia Child
1996,How To Cook Everything - The Basics,Mark Bittman
1997,Nourishing Traditions,Sally Fallon
1998,Heat,Bill Buford
1999,The Art Of Eating,M. F. K. Fisher
2000,The Fireside Cook Book,"James Beard, Alice Provensen, Martin Provensen, Mark Bittman"
2001,The Little House Cookbook,Barbara M. Walker
2002,The Silver Palate Cookbook,"Julee Rosso, Sheila Lukins"
2003,The Deal / The Mistake / The Score / The Goal / The Legacy,Elle Kennedy

In [35]:
# cleaning the title column
# straight apostrophe
books['title'] = books['title'].str.replace("'S", "'s", regex=False)

# curly apostrophe
books['title'] = books['title'].str.replace("\u2019S", "\u2019s", regex=False)

In [36]:
# manual imputting on titles for corrections
books.loc[268, 'title'] = "We Need To Talk About Kevin"
books.loc[269, 'title'] = "The Black Dahlia"
books.loc[283, 'title'] = "In Cold Blood"
books.loc[461, 'title'] = "Salem's Lot"
books.loc[665, 'title'] = "I'll Give You The Sun"
books.loc[717, 'title'] = "To All The Boys I've Loved Before (To All The Boys I've Loved Before, #1)"
books.loc[719, 'title'] = "Demian: Die Geschichte Von Emil Sinclairs Jugend"
books.loc[729, 'title'] = "Being A Witch, And Other Things I Didn't Ask For"
books.loc[890, 'title'] = "I'd Tell You I Love You, But Then I'd Have To Kill You (Gallagher Girls, #1)"
books.loc[914, 'title'] = "It Ain't Me, Babe (Hades Hangmen, #1)"
books.loc[948, 'title'] = "I'm Glad You're Dead: Preternatural Chronicles Book 1"
books.loc[1029, 'title'] = "Can't Hurt Me"
books.loc[1089, 'title'] = "Don't Panic"
books.loc[1202, 'title'] = "21 Lessons For The 21st Century"
books.loc[1320, 'title'] = "Atlas Shrugged"
books.loc[1359, 'title'] = "Don't Believe Everything You Think"
books.loc[1377, 'title'] = "You're Too Good To Feel This Bad"
books.loc[1382, 'title'] = "3AM Questions"
books.loc[1399, 'title'] = "It Didn't Start With You"
books.loc[1443, 'title'] = "The Old Patagonian Express"
books.loc[1512, 'title'] = "Animal Farm And Nineteen Eighty-Four"
books.loc[1569, 'title'] = "It Can't Happen Here"
books.loc[1587, 'title'] = "Why We're Polarized"
books.loc[1595, 'title'] = "Henry IV, Part 2"
books.loc[1623, 'title'] = "Nature, Man And Woman"
books.loc[1743, 'title'] = "The Science Fiction Hall Of Fame: Volume One"
books.loc[1751, 'title'] = "The Hitchhiker's Guide To The Galaxy: The Complete Collection"
books.loc[1785, 'title'] = "The Poems Of Emily Dickinson: Volume II"
books.loc[1910, 'title'] = "The Economic Consequences Of The Peace"
books.loc[1938, 'title'] = "L'Imagination Sociologique"
books.loc[2003, 'title'] = "The Deal / The Mistake / The Score / The Goal / The Legacy"

In [37]:
pd.reset_option('display.max_colwidth')
pd.reset_option('display.max_rows')

In [38]:
# extracting all size patterns from cover URLs (goodreads)
sizes = books['cover_img_url'].dropna().str.extractall(r'(_S[XY]\d+_)')
print(sizes[0].value_counts())

0
_SY75_    799
_SX50_    205
Name: count, dtype: int64

In [39]:
# correcting the links with SY and SX size patterns to the larger SY475 and SX318 patterns
books['cover_img_url'] = books['cover_img_url'].str.replace('_SY75_', '_SY475_', regex=False)
books['cover_img_url'] = books['cover_img_url'].str.replace('_SX50_', '_SX318_', regex=False)

In [40]:
# checking cover URLs that are not from goodreads
non_goodreads = books[~books['cover_img_url'].str.contains('goodreads', na=False, case=False)]
print(non_goodreads[['title', 'cover_img_url']])

                                                     title  \
book_id
1004                                         Wings Of Fire
1005                 The Diary Of A Young Girl- Anne Frank
1006                               Autobiography Of A Yogi
1007                                  I'M Glad My Mom Died
1008                                      Reminders Of Him
...                                                    ...
1999                                     The Art Of Eating
2000                                The Fireside Cook Book
2001                             The Little House Cookbook
2002                            The Silver Palate Cookbook
2003     The Deal / The Mistake / The Score / The Goal ...

                                             cover_img_url
book_id
1004     https://covers.openlibrary.org/b/id/9153819-L.jpg
1005     https://covers.openlibrary.org/b/id/13526331-L...
1006      https://covers.openlibrary.org/b/id/805448-L.jpg
1007     https://covers.openlibrary.org/b/id/12855985-L...
1008     https://covers.openlibrary.org/b/id/12504366-L...
...                                                    ...
1999       https://covers.openlibrary.org/b/id/14211-L.jpg
2000     https://covers.openlibrary.org/b/id/7234093-L.jpg
2001     https://covers.openlibrary.org/b/id/4940236-L.jpg
2002      https://covers.openlibrary.org/b/id/693042-L.jpg
2003     https://covers.openlibrary.org/b/id/15217419-L...

[1000 rows x 2 columns]

In [41]:
# check size suffixes from open library cover URLs
ol_books = books[books['cover_img_url'].str.contains('openlibrary', na=False, case=False)]
sizes_ol = ol_books['cover_img_url'].dropna().str.extractall(r'(-[SML]\.jpg)')
print(sizes_ol[0].value_counts())

0
-L.jpg    996
Name: count, dtype: int64

In [ ]:
# checking the genre column for standardizing names
books['genres_clean'].str.split(', ').explode().str.strip().unique().tolist()

['Young Adult',
 'Dystopia',
 'Fiction',
 'Fantasy',
 'Science Fiction',
 'Romance',
 'Adventure',
 'Classics',
 'Historical Fiction',
 'History',
 'Literature',
 'Childrens',
 'Politics',
 'Christian',
 'Contemporary',
 'Horror',
 'Gothic',
 'Psychology',
 'Philosophy',
 'Mystery',
 'Thriller',
 'Self Help',
 'Drama',
 'Humor',
 'Comedy',
 'Animals',
 'Magical Realism',
 'Time Travel',
 'Crime',
 'Women Studies',
 'Lgbt',
 'Queer',
 'Religion',
 'Nonfiction',
 'Biography',
 'Africa',
 'Travel',
 'Theatre',
 '19Th Century',
 '20Th Century',
 'Enemies To Lovers',
 'Art',
 'New Adult',
 'Love',
 'Science',
 'Human Sciences',
 'Business',
 'Education',
 'Dark',
 'Health',
 'Social Life And Customs',
 'Crimes Against',
 'Journeys',
 'Criminals',
 'Law',
 'Gardening',
 'Histoire',
 'Civilization',
 'Economic Conditions',
 'Early Works To 1800',
 'Conduct Of Life',
 'Interpersonal Relations',
 'American Poetry',
 "Children'S Poetry",
 'Cooking',
 'French']

In [59]:
# standardizing the century genre names
books['genres_clean'] = books['genres_clean'].str.replace("Children'S Poetry", "Children's Poetry", regex=False)
books['genres_clean'] = books['genres_clean'].str.replace('19Th Century', '19th Century', regex=False)
books['genres_clean'] = books['genres_clean'].str.replace('20Th Century', '20th Century', regex=False)
books['genres_clean'] = books['genres_clean'].str.replace('Lgbt', 'LGBT', regex=False)

In [60]:
# checking if standarization worked
books['genres_clean'].str.split(', ').explode().str.strip().unique().tolist()

['Young Adult',
 'Dystopia',
 'Fiction',
 'Fantasy',
 'Science Fiction',
 'Romance',
 'Adventure',
 'Classics',
 'Historical Fiction',
 'History',
 'Literature',
 'Childrens',
 'Politics',
 'Christian',
 'Contemporary',
 'Horror',
 'Gothic',
 'Psychology',
 'Philosophy',
 'Mystery',
 'Thriller',
 'Self Help',
 'Drama',
 'Humor',
 'Comedy',
 'Animals',
 'Magical Realism',
 'Time Travel',
 'Crime',
 'Women Studies',
 'LGBT',
 'Queer',
 'Religion',
 'Nonfiction',
 'Biography',
 'Africa',
 'Travel',
 'Theatre',
 '19th Century',
 '20th Century',
 'Enemies To Lovers',
 'Art',
 'New Adult',
 'Love',
 'Science',
 'Human Sciences',
 'Business',
 'Education',
 'Dark',
 'Health',
 'Social Life And Customs',
 'Crimes Against',
 'Journeys',
 'Criminals',
 'Law',
 'Gardening',
 'Histoire',
 'Civilization',
 'Economic Conditions',
 'Early Works To 1800',
 'Conduct Of Life',
 'Interpersonal Relations',
 'American Poetry',
 "Children's Poetry",
 'Cooking',
 'French']

# 04. Exporting beautiful dataframe

In [61]:
books.to_csv('../01. Data/books_streamlit.csv', index=True)