# 01. Importing Libraries

In [1]:
import os
import math
import random
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
import scipy
import numpy as np
import pandas as pd
import scipy.stats as st

# 02. Importing Data

In [3]:
books = pd.read_csv('../01. Data/books_with_clusters.csv')

# 03. Beautification of Database

In [5]:
books.head()

,book_id,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url,cluster,genres_clean
0,0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,2008,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374.0,The Hunger Games#1,NaN,NaN,NaN,NaN,NaN,4,"Young Adult, Dystopia, Fiction, Fantasy, Scien..."
1,1,Pride and Prejudice,Jane Austen,4.30,4920467.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,1813,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Classics, Romance, Fiction, Historical Fiction..."
2,2,To Kill a Mockingbird,Harper Lee,4.26,7016855.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,1960,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323.0,To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN,2,"Classics, Fiction, Historical Fiction, Literat..."
3,3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,2003,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896.0,Harry Potter#5,NaN,NaN,NaN,NaN,NaN,4,"Fantasy, Fiction, Young Adult, Fantasy, Childrens"
4,4,The Book Thief,Markus Zusak,4.39,2935583.0,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,2005,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Historical Fiction, Fiction, Young Adult, Clas..."

In [15]:
# retting index to be book_id
books.set_index('book_id', inplace=True)

In [ ]:
# changing num_ratings into INT
books['num_ratings'] = books['num_ratings'].astype('Int64')

In [16]:
books.head()

,title,author,avg_rating,num_ratings,cover_img_url,goodreads_url,source,year_published,genres,description,pages,series,isbn,publisher,language,ol_key,google_url,cluster,genres_clean
book_id,,,,,,,,,,,,,,,,,,,
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.35,10115839,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2767052-th...,GoodReads,2008,"Young Adult, Dystopia, Fiction, Fantasy, Scien...",Winning means fame and fortune. Losing means c...,374.0,The Hunger Games#1,NaN,NaN,NaN,NaN,NaN,4,"Young Adult, Dystopia, Fiction, Fantasy, Scien..."
1,Pride and Prejudice,Jane Austen,4.30,4920467,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/1885.Pride...,GoodReads,1813,"Classics, Romance, Fiction, Historical Fiction...","Since its immediate success in 1813,Pride and ...",279.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Classics, Romance, Fiction, Historical Fiction..."
2,To Kill a Mockingbird,Harper Lee,4.26,7016855,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/2657.To_Ki...,GoodReads,1960,"Classics, Fiction, Historical Fiction, School,...","""Shoot all the bluejays you want, if you can h...",323.0,To Kill a Mockingbird#1,NaN,NaN,NaN,NaN,NaN,2,"Classics, Fiction, Historical Fiction, Literat..."
3,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling,4.50,3868435,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/58613451-h...,GoodReads,2003,"Fantasy, Fiction, Young Adult, Harry Potter, M...",It's official: the evil Lord Voldemort has ret...,896.0,Harry Potter#5,NaN,NaN,NaN,NaN,NaN,4,"Fantasy, Fiction, Young Adult, Fantasy, Childrens"
4,The Book Thief,Markus Zusak,4.39,2935583,https://i.gr-assets.com/images/S/compressed.ph...,https://www.goodreads.com/book/show/19063.The_...,GoodReads,2005,"Historical Fiction, Fiction, Young Adult, Clas...",Librarian's note: An alternate cover edition c...,592.0,NaN,NaN,NaN,NaN,NaN,NaN,2,"Historical Fiction, Fiction, Young Adult, Clas..."

In [12]:
# stripping " " from title and author columns
books['title'] = books['title'].str.strip().str.strip('"')
books['author'] = books['author'].str.strip().str.strip('"')

In [14]:
# checking if books with " " in the name were stripped correctly
books[books['title'].str.contains('paint', case=False)][['title', 'genres']]

,title,genres
1121,Painted Scars,"Romance, Dark, Contemporary Romance, Adult, Di..."
1784,I Heard You Paint Houses,"Nonfiction, True Crime"

In [17]:
# removing duplicated genres from genres_list
def remove_duplicate_genres(genre_list):
    seen = []
    for genre in genre_list:
        if genre not in seen:
            seen.append(genre)
    return seen

def clean_genres_string(genres_string):
    genre_list = genres_string.split(', ')
    unique_genres = remove_duplicate_genres(genre_list)
    return ', '.join(unique_genres)

books['genres_clean'] = books['genres_clean'].apply(clean_genres_string)

In [ ]:
# checking if duplicated genres were removed correctly
books[books['author'].str.contains('Agatha Christie', case=False)][['title', 'genres_clean']]

,title,genres_clean
book_id,,
92,And Then There Were None,"Mystery, Classics, Fiction, Thriller, Crime"
215,"Murder on the Orient Express (Hercule Poirot, ...","Mystery, Classics, Fiction, Crime, Thriller"
801,"The Murder of Roger Ackroyd (Hercule Poirot, #4)","Mystery, Fiction, Classics, Crime, Thriller"
838,"Death on the Nile (Hercule Poirot, #18)","Mystery, Fiction, Classics, Crime, Thriller"
1125,The Mystery of the Blue Train,"Crimes Against, Mystery, Fiction"
1126,Endless Night,"Fiction, Mystery"
1144,Death on the Nile,"Fiction, Mystery"

# 04. Exporting beautiful dataframe

In [ ]:
books.to_csv('../01. Data/books_streamlit.csv', index=True)